# Site settings
title: Combing the Stacks
header-img: img/home-bg.png
email: spencevans@gmail.com
copyright_name: spensation
description: > # this means to ignore newlines until "baseurl:"
  An effort to synthesize an incredible amount of information.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  spensation
learn_profile: spensation
email_username: spencevans@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
